"""
Arabic name lookup: Arabic script → romanization variants.
Covers Egyptian, Levantine, Gulf, North African, South Asian Muslim naming.

Sources:
  - ALA-LC Arabic romanization
  - Hans Wehr transliteration
  - Egyptian/Gulf/Levantine colloquial transcription
  - Common HK/UK diaspora spellings
"""

ARABIC_NAME_VARIANTS: dict[str, list[str]] = {
    # ── Male ─────────────────────────────────────────────────────────────────
    "محمد": ["muhammad", "mohammed", "mohamed", "mohammad", "mohamad", "mehmed", "mehmet"],
    "أحمد": ["ahmad", "ahmed", "ahmet"],
    "علي": ["ali", "aly"],
    "عمر": ["omar", "umar", "omer"],
    "إبراهيم": ["ibrahim", "abraham", "ebrahim", "brahim"],
    "خالد": ["khaled", "khalid"],
    "يوسف": ["youssef", "yousef", "yusuf", "yusef"],
    "عبدالله": ["abdullah", "abdallah", "abd-allah"],
    "حسن": ["hassan", "hasan"],
    "حسين": ["hussein", "husain", "hussain", "hossein"],
    "عبدالرحمن": ["abdulrahman", "abd-al-rahman", "abdurrahman"],
    "سعيد": ["saeed", "said", "sa'id"],
    "سليمان": ["sulayman", "suleiman", "sulaiman", "solomon"],
    "مصطفى": ["mustafa", "mostafa"],
    "محمود": ["mahmoud", "mahmud", "mahmood"],
    "إسماعيل": ["ismail", "esmail", "ismael"],
    "عثمان": ["uthman", "osman", "othman"],
    "يحيى": ["yahya", "yahia", "yehya"],
    "إدريس": ["idris", "idrees"],
    "داود": ["dawud", "dawood", "david"],
    "صالح": ["saleh", "salih"],
    "عبدالعزيز": ["abdulaziz", "abdelaziz"],
    "طارق": ["tariq", "tarek"],
    "بلال": ["bilal", "bilel"],
    "كريم": ["karim", "kareem"],
    "جمال": ["jamal", "gamal"],
    "زياد": ["ziyad", "ziad"],
    "أيمن": ["ayman", "aymen"],
    "رامي": ["rami", "ramy"],
    "ياسر": ["yasser", "yasir"],
    "فيصل": ["faisal", "faysal"],
    "وليد": ["walid", "waleed"],
    "منير": ["munir", "mounir"],
    "شريف": ["sharif", "shareef", "sherif"],
    "هشام": ["hisham", "hesham", "hicham"],
    "حامد": ["hamid", "hamed"],
    "عادل": ["adel", "adil"],
    "رشيد": ["rashid", "rachid"],
    "ناصر": ["nasser", "nasir", "naseer"],
    "حكيم": ["hakim", "hakeem"],
    "سمير": ["samir", "samer"],
    "تامر": ["tamer", "tamir"],
    "لطفي": ["lutfi", "lotfi"],
    "ضياء": ["diya", "zia"],
    "جهاد": ["jihad", "djihad"],
    "مجدي": ["magdi", "majdi"],
    "صفوان": ["safwan", "sofwan"],
    "أسامة": ["osama", "usama", "ousama"],
    "زكريا": ["zakariya", "zechariah", "zacharia"],
    # ── Female ────────────────────────────────────────────────────────────────
    "فاطمة": ["fatima", "fatimah", "fatema"],
    "عائشة": ["aisha", "ayesha", "aesha"],
    "مريم": ["maryam", "mariam", "miriam"],
    "زينب": ["zainab", "zaynab", "zeinab"],
    "سارة": ["sara", "sarah"],
    "نور": ["noor", "nur", "noura"],
    "أمينة": ["amina", "aminah", "ameena"],
    "هند": ["hind", "hend"],
    "سلمى": ["salma", "saloma"],
    "رنا": ["rana", "rania"],
    "نادية": ["nadia", "nadya"],
    "سمية": ["samia", "samya"],
    "منى": ["mona", "muna"],
    "رانيا": ["rania", "ranya"],
    "ليلى": ["layla", "leila", "leyla", "laila"],
    "خديجة": ["khadija", "khadijah"],
    "أسماء": ["asma", "asmaa"],
    "سناء": ["sana", "sanaa"],
    "إيمان": ["iman", "eiman"],
    "دينا": ["dina", "deena"],
    "ياسمين": ["yasmin", "jasmine", "yasmine"],
    "نوال": ["nawal", "naouwal"],
    "هدى": ["huda", "houda"],
    "وفاء": ["wafa", "wafaa"],
    "سلوى": ["salwa", "solwa"],
    "رحمة": ["rahma", "rahmat"],
    "لبنى": ["lubna", "loubna"],
    "سحر": ["sahar", "sehar"],
    "غادة": ["ghada", "ghade"],
    "ريم": ["reem", "rim"],
    "شيرين": ["shirin", "shireen", "cherine"],
    "حنان": ["hanan", "hanane"],
    "شيماء": ["shayma", "chaima"],
    "ملاك": ["malak", "melak"],
    "نجوى": ["najwa", "nagwa"],
    "بسمة": ["basma", "bassma"],
    "رشا": ["rasha", "racha"],
    "لمياء": ["lamia", "lamya"],
    "عبير": ["abeer", "abir"],
    "روان": ["rawan", "rowan"],
    "زهراء": ["zahra", "zahrae", "zohra"],
    "ميسون": ["maysun", "maisun"],
    "ثريا": ["thuraya", "thoraya", "soraiya"],
}
