"""
Chinese surname lookup: Simplified Han → romanization variants.
Traditional forms reduce to Simplified via opencc before lookup.
Covers Mandarin (Pinyin), Cantonese (Jyutping/Yale), Hokkien/Teochew/Hakka, Wade-Giles.

Key: always Simplified character. Traditional 陳 → opencc → 陈 → lookup.
Romanizations: all lowercase.

Sources:
  - 百家姓 census + modern CNKI surname frequency data
  - HK Immigration Department romanization standards
  - SEA Chinese (Singapore/Malaysia) naming conventions
  - Jyutping romanization for Cantonese
"""

CHINESE_SURNAME_VARIANTS: dict[str, list[str]] = {
    # ── Top 10 (covers ~40% of Chinese population) ──────────────────────────
    "王": ["wang", "wong", "ong", "ang"],
    "李": ["li", "lee", "lei", "ly"],
    "张": ["張", "zhang", "chang", "cheung", "cheong", "teo", "tio", "chong", "chung", "jeung"],
    "刘": ["劉", "liu", "lau", "lew", "low", "liew"],
    "陈": ["陳", "chen", "chan", "tan", "chin", "zen", "chern"],
    "杨": ["楊", "yang", "yeung", "yeong", "yong", "young", "io"],
    "黄": ["黃", "huang", "wong", "ng", "oei", "uy", "wee", "way", "huong"],
    "赵": ["趙", "zhao", "chao", "chew", "chu", "chiu", "tio", "dzao"],
    "吴": ["吳", "wu", "ng", "goh", "ngo", "woo", "ou", "gou"],
    "周": ["zhou", "chow", "jou", "chu", "chou", "tsou", "chau"],
    # ── 11-50 ────────────────────────────────────────────────────────────────
    "徐": ["xu", "hui", "tsui", "chui", "kho", "khoo", "zee"],
    "孙": ["sun", "suen", "soon"],
    "马": ["ma", "mah"],
    "朱": ["zhu", "chu", "choo"],
    "胡": ["hu", "woo", "foo"],
    "郭": ["guo", "kwok", "kuok", "kok", "quek"],
    "何": ["he", "ho", "hoe"],
    "高": ["gao", "ko", "cao", "koh"],
    "林": ["lin", "lim", "lam", "ling", "lum"],
    "郑": ["鄭", "zheng", "cheng", "teh", "tay", "tee", "ching", "zeng"],
    "谢": ["謝", "xie", "tse", "chia", "sia", "ze"],
    "罗": ["羅", "luo", "lo", "law", "loh"],
    "梁": ["liang", "leung", "neo"],
    "宋": ["song", "soong", "sung"],
    "唐": ["tang", "tong", "dong", "thong"],
    "许": ["許", "xu", "hui", "kho", "khoo", "heui", "hee"],
    "韩": ["韓", "han", "hon", "hann"],
    "冯": ["馮", "feng", "fung", "fong", "hong", "foong"],
    "邓": ["鄧", "deng", "tang", "teng", "ding"],
    "曹": ["cao", "chou", "cho"],
    "彭": ["peng", "phang", "pheng"],
    "曾": ["zeng", "tsang", "tseng"],
    "萧": ["蕭", "xiao", "hsiao", "siu", "sieu", "sew"],
    "田": ["tian", "tin"],
    "董": ["dong", "tung"],
    "袁": ["yuan", "yuen"],
    "潘": ["pan", "poon", "pua"],
    "于": ["yu", "yee", "ee"],
    "蒋": ["蔣", "jiang", "chiang", "cheung", "tsiang"],
    "蔡": ["cai", "chua", "tsai", "chai"],
    # ── 51-100 ────────────────────────────────────────────────────────────────
    "余": ["yu", "yee", "ee"],
    "苏": ["蘇", "su", "soo", "soh", "see"],
    "叶": ["葉", "ye", "yap", "ip", "yip", "jip"],
    "吕": ["呂", "lu", "lui", "loo", "lv"],
    "魏": ["wei", "ngai"],
    "程": ["cheng", "ching"],
    "沈": ["shen", "shum", "sim"],
    "江": ["jiang", "kong", "kang"],
    "傅": ["fu", "foo", "phu"],
    "华": ["華", "hua", "wah", "wa"],
    "钟": ["鍾", "zhong", "chung", "tung", "tsong"],
    "卢": ["盧", "lu", "lo", "loh", "luu"],
    "汪": ["wang", "ong"],
    "戴": ["dai", "tai"],
    "崔": ["cui", "choi", "tsui"],
    "任": ["ren", "yam"],
    "陆": ["陸", "lu", "luk", "look"],
    "廖": ["liao", "lew", "liu"],
    "姚": ["yao", "yeu", "yiu"],
    "方": ["fang", "fong", "hong"],
    "金": ["jin", "kim", "gim", "kam"],
    "邱": ["qiu", "khoo", "kew", "kiu"],
    "谭": ["譚", "tan", "tam", "tham"],
    "韦": ["wei", "wee"],
    "贾": ["jia", "ka"],
    "邹": ["zou", "chow", "tsou"],
    "石": ["shi", "shek"],
    "熊": ["xiong", "hung"],
    "孟": ["meng", "mang"],
    "秦": ["qin", "chin"],
    "薛": ["xue", "sit"],
    "侯": ["hou", "hau"],
    "雷": ["lei", "lui"],
    "白": ["bai", "pak"],
    "龙": ["龍", "long", "loong", "lung"],
    "段": ["duan", "tuan"],
    "郝": ["hao", "hak"],
    "孔": ["kong", "hung"],
    "邵": ["shao", "shiu"],
    "史": ["shi", "see"],
    "毛": ["mao", "mo"],
    "常": ["chang", "seong"],
    "万": ["wan", "man"],
    "顾": ["gu", "ku"],
    "赖": ["lai", "lye"],
    "武": ["wu", "moo"],
    "康": ["kang", "hong"],
    "贺": ["he", "ho"],
    "严": ["yan", "yim", "ngeam"],
    "尹": ["yin", "wan"],
    "钱": ["錢", "qian", "chien", "chin"],
    "施": ["shi", "see", "si"],
    "洪": ["hong", "ang"],
    "龚": ["gong", "kung"],
    # ── 101-200 ────────────────────────────────────────────────────────────────
    "姜": ["jiang", "keong"],
    "范": ["fan", "fam", "huan"],
    "杜": ["du", "to", "toh"],
    "丁": ["ding", "teng"],
    "牛": ["niu", "ngau"],
    "翁": ["weng", "yung", "ang"],
    "甘": ["gan", "gam", "kam"],
    "肖": ["xiao", "siu"],
    "欧阳": ["ouyang", "au-yeung"],
    "司徒": ["situ", "szeto", "sze-to"],
    "诸葛": ["zhuge", "chu-kot"],
    "游": ["you", "yau", "yu"],
    "向": ["xiang", "heung"],
    "管": ["guan", "koon"],
    "文": ["wen", "man", "mun"],
    "岑": ["cen", "sam", "sim"],
    "麦": ["mai", "mak"],
    "章": ["zhang", "cheung"],
    "欧": ["ou", "au"],
    "项": ["xiang", "hong"],
    "祝": ["zhu", "juk"],
    "封": ["feng", "fung"],
    "房": ["fang", "fong"],
    "邢": ["xing", "hing"],
    "庄": ["zhuang", "chong"],
    "温": ["wen", "wan", "wun"],
    "花": ["hua", "fa"],
    "涂": ["tu", "toh"],
    "鲁": ["lu", "lo"],
    "苟": ["gou", "kau"],
    "缪": ["miao", "miu"],
    "卓": ["zhuo", "cheuk"],
    "池": ["chi", "chee"],
    "凌": ["ling", "leng"],
    "桂": ["gui", "kwai"],
    "蒲": ["pu", "po"],
    "连": ["lian", "lin"],
    "柳": ["liu", "lau"],
    "司": ["si", "see"],
    "仇": ["chou", "kau"],
    "贝": ["bei", "bui"],
    "伍": ["wu", "ng"],
    "洗": ["xian", "sin"],
    "舒": ["shu", "shoo"],
    "商": ["shang", "soeng"],
    "关": ["關", "guan", "kwan", "kwaan"],
}
