"""
Japanese surname lookup: kanji → Hepburn romanization variants.
Standard Hepburn + modified variants (ou/o/oh, uu/u, etc.).

Sources:
  - MEXT romanization guidelines
  - Hepburn standard (ALA-LC) + common Western variants
"""

JAPANESE_SURNAME_VARIANTS: dict[str, list[str]] = {
    "佐藤": ["sato", "satou", "satoh"],
    "鈴木": ["suzuki"],
    "高橋": ["takahashi"],
    "田中": ["tanaka"],
    "伊藤": ["ito", "itou", "itoh"],
    "渡辺": ["watanabe"],
    "山本": ["yamamoto"],
    "中村": ["nakamura"],
    "小林": ["kobayashi"],
    "加藤": ["kato", "katou", "katoh"],
    "吉田": ["yoshida"],
    "山田": ["yamada"],
    "佐々木": ["sasaki"],
    "山口": ["yamaguchi"],
    "松本": ["matsumoto"],
    "井上": ["inoue", "inouye"],
    "木村": ["kimura"],
    "林": ["hayashi"],
    "斎藤": ["saito", "saitou", "saitoh"],
    "清水": ["shimizu"],
    "池田": ["ikeda"],
    "橋本": ["hashimoto"],
    "阿部": ["abe"],
    "森": ["mori"],
    "石川": ["ishikawa"],
    "山崎": ["yamazaki", "yamasaki"],
    "前田": ["maeda"],
    "岡田": ["okada"],
    "長谷川": ["hasegawa"],
    "藤田": ["fujita"],
    "近藤": ["kondo", "kondou", "kondoh"],
    "石田": ["ishida"],
    "後藤": ["goto", "gotou", "gotoh"],
    "村上": ["murakami"],
    "坂本": ["sakamoto"],
    "遠藤": ["endo", "endou", "endoh"],
    "青木": ["aoki"],
    "藤井": ["fujii"],
    "西村": ["nishimura"],
    "福田": ["fukuda"],
    "太田": ["ota", "ohta", "oota"],
    "三浦": ["miura"],
    "岡本": ["okamoto"],
    "松田": ["matsuda"],
    "中島": ["nakajima", "nakashima"],
    "浜田": ["hamada"],
    "藤原": ["fujiwara"],
    "小川": ["ogawa"],
    "中田": ["nakata", "nakada"],
    "上田": ["ueda"],
    "原田": ["harada"],
    "野口": ["noguchi"],
    "今井": ["imai"],
    "川口": ["kawaguchi"],
    "千葉": ["chiba"],
    "内田": ["uchida"],
    "大野": ["ohno", "ono"],
    "西田": ["nishida"],
    "河野": ["kono", "kawano"],
    "武田": ["takeda"],
    "金子": ["kaneko"],
    "中野": ["nakano"],
    "杉山": ["sugiyama"],
    "石原": ["ishihara"],
    "宮崎": ["miyazaki"],
    "山下": ["yamashita"],
    "大塚": ["otsuka"],
    "岩崎": ["iwasaki"],
    "広瀬": ["hirose"],
    "横山": ["yokoyama"],
    "辻": ["tsuji"],
    "菊地": ["kikuchi"],
    "佐野": ["sano"],
    "丸山": ["maruyama"],
    "樋口": ["higuchi"],
    "岩田": ["iwata"],
    "村田": ["murata"],
    "久保": ["kubo"],
    "上野": ["ueno"],
    "野村": ["nomura"],
    "藤本": ["fujimoto"],
    "古川": ["furukawa"],
    "平野": ["hirano"],
    "大久保": ["okubo"],
    "田村": ["tamura"],
    "中山": ["nakayama"],
    "水野": ["mizuno"],
    "西川": ["nishikawa"],
    "服部": ["hattori"],
    "黒田": ["kuroda"],
    "谷口": ["taniguchi"],
    "篠原": ["shinohara"],
    "北村": ["kitamura"],
    "栗原": ["kurihara"],
    "大西": ["onishi"],
    "木下": ["kinoshita"],
    "安田": ["yasuda"],
    "田口": ["taguchi"],
    "小野": ["ono"],
    "松井": ["matsui"],
    "山内": ["yamauchi"],
    "平田": ["hirata"],
    "川村": ["kawamura"],
    "本田": ["honda"],
    "高田": ["takada", "takata"],
    "竹内": ["takeuchi"],
    "秋山": ["akiyama"],
    "富田": ["tomita"],
    "石井": ["ishii"],
    "宮田": ["miyata"],
    "浅野": ["asano"],
    "松尾": ["matsuo"],
    "安藤": ["ando", "andou"],
    "関": ["seki"],
    "奥田": ["okuda"],
    "横田": ["yokota"],
    "矢野": ["yano"],
    "神田": ["kanda"],
    "沼田": ["numata"],
    "中川": ["nakagawa"],
    "藤沢": ["fujisawa"],
    "小松": ["komatsu"],
    "内山": ["uchiyama"],
    "高山": ["takayama"],
    "早川": ["hayakawa"],
    "永田": ["nagata"],
    "川上": ["kawakami"],
    "岡村": ["okamura"],
    "野田": ["noda"],
    "三宅": ["miyake"],
    "牧": ["maki"],
    "長島": ["nagashima"],
    "渡部": ["watabe"],
    "坂田": ["sakata"],
    "岸": ["kishi"],
    "菅": ["suga", "kan"],
    "麻生": ["aso"],
    "小泉": ["koizumi"],
    "安倍": ["abe"],
    "鳩山": ["hatoyama"],
    "福田": ["fukuda"],
    "細川": ["hosokawa"],
    "竹下": ["takeshita"],
    "中曽根": ["nakasone"],
    "田中": ["tanaka"],
}
